{
  "language": "node_js",
  "os": [
    "mac"
  ],
  "dist": "xenial",
  "node_js": [
    "-\"node\""
  ],
  "cache": {
    "npm": true,
    "directories": [
      "~/.cache"
    ]
  },
  "install": [
    "npm ci",
    "npm run build"
  ],
  "before_script": [
    "npm start -- --silent &"
  ],
  "script": [
    "$(npm bin)/cypress run"
  ]
}
