export const charityCategories = [
  {categoryId:'A', categoryDesc:"Arts, Culture and Humanities"},
  {categoryId:'B', categoryDesc:"Educational Institutions and Related Activities"},
  {categoryId:'C', categoryDesc:"Environmental Quality, Protection and Beautification"},
  {categoryId:'D', categoryDesc:"Animal-Related"},
  {categoryId:'E', categoryDesc:"Health - General and Rehabilitative"},
  {categoryId:'F', categoryDesc:"Mental Health, Crisis Intervention"},
  {categoryId:'G', categoryDesc:"Diseases, Disorders, Medical Disciplines"},
  {categoryId:'H', categoryDesc:"Medical Research"},
  {categoryId:'I', categoryDesc:"Crime, Legal-Related"},
  {categoryId:'J', categoryDesc:"Employment, Job-Related"},
  {categoryId:'K', categoryDesc:"Food, Agriculture and Nutrition"},
  {categoryId:'L', categoryDesc:"Housing, Shelter"},
  {categoryId:'M', categoryDesc:"Public Safety, Disaster Preparedness and Relief"},
  {categoryId:'N', categoryDesc:"Recreation, Sports, Leisure, Athletics"},
  {categoryId:'O', categoryDesc:"Youth Development"},
  {categoryId:'P', categoryDesc:"Human Services - Multipurpose and Other"},
  {categoryId:'Q', categoryDesc:"International, Foreign Affairs and National Security"},
  {categoryId:'R', categoryDesc:"Civil Rights, Social Action, Advocacy"},
  {categoryId:'S', categoryDesc:"Community Improvement, Capacity Building"},
  {categoryId:'T', categoryDesc:"Philanthropy, Voluntarism and Grantmaking Foundations"},
  {categoryId:'U', categoryDesc:"Science and Technology Research Institutes, Services"},
  {categoryId:'V', categoryDesc:"Social Science Research Institutes, Services"},
  {categoryId:'W', categoryDesc:"Public, Society Benefit - Multipurpose and Other"},
  {categoryId:'X', categoryDesc:"Religion-Related, Spiritual Development"},
  {categoryId:'Y', categoryDesc:"Mutual\/Membership Benefit Organizations, Other"}
];

export const stateInputs = [
  {state: "Alabama", code: "AL"},
  {state: "Alaska", code: "AK"},
  {state: "Arizona", code: "AZ"},
  {state: "Arkansas", code: "AR"},
  {state: "California", code: "CA"},
  {state: "Colorado", code: "CO"},
  {state: "Connecticut", code: "CT"},
  {state: "Delaware", code: "DE"},
  {state: "Florida", code: "FL"},
  {state: "Georgia", code: "GA"},
  {state: "Hawaii", code: "HI"},
  {state: "Idaho", code: "ID"},
  {state: "Illinois", code: "IL"},
  {state: "Indiana", code: "IN"},
  {state: "Iowa", code: "IA"},
  {state: "Kansas", code: "KS"},
  {state: "Kentucky", code: "KY"},
  {state: "Louisiana", code: "LA"},
  {state: "Maine", code: "ME"},
  {state: "Maryland", code: "MD"},
  {state: "Massachusetts", code: "MA"},
  {state: "Michigan", code: "MI"},
  {state: "Minnesota", code: "MN"},
  {state: "Mississippi", code: "MS"},
  {state: "Missouri", code: "MO"},
  {state: "Montana", code: "MT"},
  {state: "Nebraska", code: "NE"},
  {state: "Nevada", code: "NV"},
  {state: "New Hampshire", code: "NH"},
  {state: "New Jersey", code: "NJ"},
  {state: "New Mexico", code: "NM"},
  {state: "New York", code: "NY"},
  {state: "North Carolina", code: "NC"},
  {state: "North Dakota", code: "ND"},
  {state: "Ohio", code: "OH"},
  {state: "Oklahoma", code: "OK"},
  {state: "Oregon", code: "OR"},
  {state: "Pennsylvania", code: "PA"},
  {state: "Rhode Island", code: "RI"},
  {state: "South Carolina", code: "SC"},
  {state: "South Dakota", code: "SD"},
  {state: "Tennessee", code: "TN"},
  {state: "Texas", code: "TX"},
  {state: "Utah", code: "UT"},
  {state: "Vermont", code: "VT"},
  {state: "Virginia", code: "VA"},
  {state: "Washington", code: "WA"},
  {state: "West Virginia", code: "WV"},
  {state: "Wisconsin", code: "WI"},
  {state: "Wyoming", code: "WY"}
]
