export const categoryData = [
  {id:'A', value:"Arts, Culture and Humanities"},
  {id:'B', value:"Educational Institutions and Related Activities"},
  {id:'C', value:"Environmental Quality, Protection and Beautification"},
  {id:'D', value:"Animal-Related"},
  {id:'E', value:"Health - General and Rehabilitative"},
  {id:'F', value:"Mental Health, Crisis Intervention"},
  {id:'G', value:"Diseases, Disorders, Medical Disciplines"},
  {id:'H', value:"Medical Research"},
  {id:'I', value:"Crime, Legal-Related"},
  {id:'J', value:"Employment, Job-Related"},
  {id:'K', value:"Food, Agriculture and Nutrition"},
  {id:'L', value:"Housing, Shelter"},
  {id:'M', value:"Public Safety, Disaster Preparedness and Relief"},
  {id:'N', value:"Recreation, Sports, Leisure, Athletics"},
  {id:'O', value:"Youth Development"},
  {id:'P', value:"Human Services - Multipurpose and Other"},
  {id:'Q', value:"International, Foreign Affairs and National Security"},
  {id:'R', value:"Civil Rights, Social Action, Advocacy"},
  {id:'S', value:"Community Improvement, Capacity Building"},
  {id:'T', value:"Philanthropy, Voluntarism and Grantmaking Foundations"},
  {id:'U', value:"Science and Technology Research Institutes, Services"},
  {id:'V', value:"Social Science Research Institutes, Services"},
  {id:'W', value:"Public, Society Benefit - Multipurpose and Other"},
  {id:'X', value:"Religion-Related, Spiritual Development"},
  {id:'Y', value:"Mutual\/Membership Benefit Organizations, Other"}
];

export const stateData = [
  {id: "Alabama", value: "AL"},
  {id: "Alaska", value: "AK"},
  {id: "Arizona", value: "AZ"},
  {id: "Arkansas", value: "AR"},
  {id: "California", value: "CA"},
  {id: "Colorado", value: "CO"},
  {id: "Connecticut", value: "CT"},
  {id: "Delaware", value: "DE"},
  {id: "Florida", value: "FL"},
  {id: "Georgia", value: "GA"},
  {id: "Hawaii", value: "HI"},
  {id: "Idaho", value: "ID"},
  {id: "Illinois", value: "IL"},
  {id: "Indiana", value: "IN"},
  {id: "Iowa", value: "IA"},
  {id: "Kansas", value: "KS"},
  {id: "Kentucky", value: "KY"},
  {id: "Louisiana", value: "LA"},
  {id: "Maine", value: "ME"},
  {id: "Maryland", value: "MD"},
  {id: "Massachusetts", value: "MA"},
  {id: "Michigan", value: "MI"},
  {id: "Minnesota", value: "MN"},
  {id: "Mississippi", value: "MS"},
  {id: "Missouri", value: "MO"},
  {id: "Montana", value: "MT"},
  {id: "Nebraska", value: "NE"},
  {id: "Nevada", value: "NV"},
  {id: "New Hampshire", value: "NH"},
  {id: "New Jersey", value: "NJ"},
  {id: "New Mexico", value: "NM"},
  {id: "New York", value: "NY"},
  {id: "North Carolina", value: "NC"},
  {id: "North Dakota", value: "ND"},
  {id: "Ohio", value: "OH"},
  {id: "Oklahoma", value: "OK"},
  {id: "Oregon", value: "OR"},
  {id: "Pennsylvania", value: "PA"},
  {id: "Rhode Island", value: "RI"},
  {id: "South Carolina", value: "SC"},
  {id: "South Dakota", value: "SD"},
  {id: "Tennessee", value: "TN"},
  {id: "Texas", value: "TX"},
  {id: "Utah", value: "UT"},
  {id: "Vermont", value: "VT"},
  {id: "Virginia", value: "VA"},
  {id: "Washington", value: "WA"},
  {id: "West Virginia", value: "WV"},
  {id: "Wisconsin", value: "WI"},
  {id: "Wyoming", value: "WY"}
]
